version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
    filters:
      branches:
        only:
          - master
  test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
