version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  acceptance_test_1:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: echo "RUN acceptance_test_1"
  acceptance_test_2:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: echo "RUN acceptance_test_2"
  acceptance_test_3:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: echo "RUN acceptance_test_3"
  deploy:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - acceptance_test_1:
          requires:
            - build
      - acceptance_test_2:
          requires:
            - build
      - acceptance_test_3:
          requires:
            - build
      - deploy:
          requires:
            - acceptance_test_1
            - acceptance_test_2
            - acceptance_test_3
