export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_COMICS_PENDING = 'REQUEST_COMICS_PENDING';
export const REQUEST_COMICS_SUCCESS = 'REQUEST_COMICS_SUCCESS';
export const REQUEST_COMICS_FAILED = 'REQUEST_COMICS_FAILED';